name: CI
on: push

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: ubuntu-latest
            #shell: nix-shell --run
            shell: bash -lc
          - os: windows-latest
            shell: msys2do.cmd
      fail-fast: false
    env:
      SHELL: ${{ matrix.shell }}
      MSYS_NO_PATHCONV: 1
    steps:
      - uses: numworks/setup-msys2@v1
        if: matrix.os == 'windows-latest'
      - run: $SHELL 'echo $PATH && ls -l'
      - run: echo $PATH && ls -l
        shell: $RUNNER_TEMP\msys64\usr\bin\bash.exe
        if: always()
      - run: echo $PATH && ls -l
        shell: msys2do.cmd
        if: always()
