name: CI
on: push

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: ubuntu-latest
            #shell: nix-shell --run
            shell: bash -lc
          - os: windows-latest
            shell: msys2do.cmd
      fail-fast: false
    env:
      SHELL: ${{ matrix.shell }}
      MSYS_NO_PATHCONV: 1
    steps:
      - uses: numworks/setup-msys2@v1
        if: matrix.os == 'windows-latest'
      - run: |
          & $SHELL "ls -l; which ls"
        env:
          SHELL: $RUNNER_TEMP\msys64\usr\bin\bash.exe -lc
        if: always()
      - run: "& msys2do ls -l; which ls"
        if: always()
      - run: msys2do ls -l; which ls < /dev/null
        shell: cmd
        if: always()
      - run: msys2do ls -l; which ls ^< /dev/null
        shell: cmd
        if: always()

