name: CI
on: push

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: ubuntu-latest
            #shell: nix-shell --run
            shell: bash -lc
          - os: windows-latest
            shell: D:\msys64\usr\bin\bash --noprofile --norc -eo pipefail
      fail-fast: false
    env:
      SHELL: ${{ matrix.shell }}
    steps:
      - uses: numworks/setup-msys2@v1
        if: matrix.os == 'windows-latest'
      - run: eval $SHELL 'echo $PATH && ls -l'
        shell: bash
      - run: msys2do.cmd 'echo $PATH && ls -l'
        shell: bash
